name: Deploy to Live Channel

on:
  push:
    branches:
      - main
    # Optionally configure to run only for specific files. For example:
    # paths:
    # - "website/**"

env:
  PROJECT_ID: hanaref-backend-462009
  SERVICE: hanaref-backend
  REGION: europe-west4

#jobs:
#  deploy_live_website:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      # Add any build steps here. For example:
#      # - run: npm ci && npm run build
#      - uses: FirebaseExtended/action-hosting-deploy@v0
#        with:
#          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
#          projectId: hanardept-backend
#          channelId: live


jobs:
  deploy_live_website:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - uses: 'google-github-actions/auth@v2'
      with:
        #workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        credentials_json: "${{ secrets.GCP_GH_SVC_ACCOUNT_CREDS }}"

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          # NOTE: If required, update to the appropriate source folder
          source: ./
        

    - name: 'Use output'
      run: 'curl "${{ steps.deploy.outputs.url }}"'          
